version: "3.0"

services:
  testui:
    build:
      context: ./docker/testui
    image: cfwheels-testui:v1.0.2
    ports:
      - "3000:8080"

  # lucee5:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/lucee5/Dockerfile
  #   image: wheels-test-lucee5:v3.0.0
  #   volumes:
  #     - .:/wheels-test-suite
  #     - ~/.CommandBox/artifacts:/root/.CommandBox/artifacts
  #     - type: bind
  #       source: ./docker/lucee5/server.json
  #       target: /wheels-test-suite/server.json
  #     - type: bind
  #       source: ./docker/lucee5/settings.cfm
  #       target: /wheels-test-suite/config/settings.cfm
  #   ports:
  #     - "60005:8080"

  # lucee6:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/lucee6/Dockerfile
  #   image: cfwheels-test-lucee6:v1.0.2
  #   volumes:
  #     - ./:/cfwheels-test-suite
  #     - ~/.CommandBox/artifacts:/root/.CommandBox/artifacts
  #     - type: bind
  #       source: ./docker/lucee6/server.json
  #       target: /cfwheels-test-suite/server.json
  #     - type: bind
  #       source: ./docker/lucee5/settings.cfm
  #       target: /cfwheels-test-suite/app/config/settings.cfm
  #   ports:
  #     - "60006:8080"

  # adobe2018:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/adobe2018/Dockerfile
  #   image: cfwheels-test-adobe2018:v1.0.2
  #   volumes:
  #     - ./:/cfwheels-test-suite
  #     - ~/.CommandBox/artifacts:/root/.CommandBox/artifacts
  #     - type: bind
  #       source: ./docker/adobe2018/server.json
  #       target: /cfwheels-test-suite/server.json
  #     - type: bind
  #       source: ./docker/adobe2018/settings.cfm
  #       target: /cfwheels-test-suite/app/config/settings.cfm
  #   ports:
  #     - "62018:8080"

  # adobe2021:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/adobe2021/Dockerfile
  #   image: cfwheels-test-adobe2021:v1.0.2
  #   volumes:
  #     - ./:/cfwheels-test-suite
  #     - ~/.CommandBox/artifacts:/root/.CommandBox/artifacts
  #     - type: bind
  #       source: ./docker/adobe2021/server.json
  #       target: /cfwheels-test-suite/server.json
  #     - type: bind
  #       source: ./docker/adobe2021/settings.cfm
  #       target: /cfwheels-test-suite/app/config/settings.cfm
  #   ports:
  #     - "62021:8080"

  # adobe2023:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/adobe2023/Dockerfile
  #   image: cfwheels-test-adobe2023:v1.0.1
  #   volumes:
  #     - ./:/cfwheels-test-suite
  #     - ~/.CommandBox/artifacts:/root/.CommandBox/artifacts
  #     - type: bind
  #       source: ./docker/adobe2023/server.json
  #       target: /cfwheels-test-suite/server.json
  #     - type: bind
  #       source: ./docker/adobe2023/settings.cfm
  #       target: /cfwheels-test-suite/app/config/settings.cfm
  #   ports:
  #     - "62023:8080"

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wheelstestdb
      MYSQL_DATABASE: wheelstestdb
      MYSQL_USER: wheelstestdb
      MYSQL_PASSWORD: wheelstestdb
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: wheelstestdb
      POSTGRES_PASSWORD: wheelstestdb
      POSTGRES_INITDB_ARGS: --auth-host=md5
    ports:
      - "5432:5432"

  sqlserver:
    build:
      context: ./
      dockerfile: ./docker/sqlserver/Dockerfile
    image: cfwheels-sqlserver:v1.0.1
    environment:
      MSSQL_SA_PASSWORD: x!bsT8t60yo0cTVTPq
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    ports:
      - "1433:1433"